version: "3.8"

services:
  test-db:
    image: mariadb:lts-ubi9
    container_name: blindorder-test-db
    environment:
      MYSQL_ROOT_PASSWORD: test_root_password
      MYSQL_DATABASE: blindorder_test
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test_password
    ports:
      - "3307:3306"
    volumes:
      - ./backend/tests/fixtures/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-ptest_root_password",
        ]
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      - test-network

  test-runner:
    build:
      context: ./backend
      dockerfile: Dockerfile.test
    container_name: blindorder-test-runner
    environment:
      NODE_ENV: test
      DATABASE_TYPE: mariadb
      DATABASE_HOST: test-db
      DATABASE_PORT: 3306
      DATABASE_USER: test_user
      DATABASE_PASSWORD: test_password
      DATABASE_NAME: blindorder_test
    depends_on:
      test-db:
        condition: service_healthy
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npm run test:all
    networks:
      - test-network

  integration-test:
    build:
      context: ./backend
      dockerfile: Dockerfile.test
    container_name: blindorder-integration-test
    environment:
      NODE_ENV: test
      DATABASE_TYPE: sqlite
      TEST_MODE: integration
    volumes:
      - ./backend:/app
      - /app/node_modules
      - test-data:/app/data
    command: npm run test:integration
    networks:
      - test-network

volumes:
  test-data:

networks:
  test-network:
    driver: bridge
