version: "3.8"

services:
  test-backend:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: blindorder-test
    environment:
      NODE_ENV: test
      DATABASE_TYPE: sqlite
      PORT: 3002
    command: npm run test:integration
    networks:
      - test-network

networks:
  test-network:
    driver: bridge
