version: "3.8"

services:
  mariadb:
    image: mariadb:lts-ubi9
    container_name: blindorder-mariadb-dev
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: blindorder_dev
      MYSQL_USER: blindorder_dev
      MYSQL_PASSWORD: dev_password
    ports:
      - "3306:3306"
    volumes:
      - mariadb_dev_data:/var/lib/mysql
      - ./docker/mariadb/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - blindorder-network
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-proot_password",
        ]
      interval: 10s
      timeout: 10s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: blindorder-backend-dev
    restart: unless-stopped
    environment:
      NODE_ENV: development
      DB_HOST: mariadb
      DB_PORT: "3306"
      DB_USERNAME: blindorder_dev
      DB_PASSWORD: dev_password
      DB_NAME: blindorder_dev
    ports:
      - "3001:3001"
    volumes:
      - ./src:/app/src:ro
      - ./src/config:app/config:ro
      - ./logs:/app/logs
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      - blindorder-network

volumes:
  mariadb_dev_data:
    driver: local

networks:
  blindorder-network:
    driver: bridge
