name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install dependencies - Root
        run: npm ci

      - name: Install dependencies - Backend
        working-directory: ./backend
        run: npm ci

      - name: Install dependencies - Frontend
        working-directory: ./frontend
        run: npm ci

      - name: Lint Backend
        working-directory: ./backend
        run: npm run lint || true

      - name: Build Backend
        working-directory: ./backend
        run: npm run build

      - name: Run Unit Tests
        working-directory: ./backend
        run: npm run test:unit

      - name: Run Integration Tests
        working-directory: ./backend
        run: npm run test:integration

      - name: Build Frontend
        working-directory: ./frontend
        run: npm run build-only

  coverage:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          cache: "npm"

      - name: Install dependencies - Root
        run: npm ci

      - name: Install dependencies - Backend
        working-directory: ./backend
        run: npm ci

      - name: Run Tests with Coverage
        working-directory: ./backend
        run: npm run test:coverage

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          directory: ./backend/coverage
          flags: backend
          fail_ci_if_error: false
